name: Build container images

on:
  push:
    paths:
      - '*/Dockerfile'
  workflow_dispatch:
    inputs:
      apps:
        description: 'Comma-separated list of applications to build (e.g., caddy,patroni)'
        required: false

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      apps_to_build: ${{ steps.detect.outputs.apps_to_build }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch the current and previous commit to ensure `github.event.before` is available
          fetch-depth: 2

      - name: Detect Applications to Build
        id: detect
        run: |
          bash .github/scripts/detect_apps.sh "${{ github.event.inputs.apps }}" "${{ github.event.before }}" "${{ github.sha }}"
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

  build:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ needs.detect.outputs.apps_to_build != '' && needs.detect.outputs.apps_to_build != 'No apps detected.' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        run: |
          bash .github/build_and_push.sh "${{ needs.detect.outputs.apps_to_build }}"
